[tools]
# --- 构建 & 任务运行 ---
just = "latest" # 任务运行器，Makefile 现代化替代品

# --- 代码质量、规范与安全门禁 ---
shellcheck = "latest" # Shell 脚本静态语法分析
shfmt = "latest" # Shell 脚本格式化
actionlint = "latest" # GitHub Actions 工作流静态校验
yamllint = "latest" # YAML 语法与缩进静态检测
rumdl = "latest" # Markdown 格式化与规范校验
gitleaks = "latest" # 密钥与敏感信息静态扫描
trivy = "latest" # 容器与 K8s 清单安全合规与错配扫描器
lefthook = "latest" # 极速 Git Hooks 管理器

# --- 敏感机密声明式管理 ---
kubeseal = "latest" # Bitnami Sealed Secrets 离线公钥加密 CLI

# --- Kubernetes 核心与 GitOps 工具链 ---
kubectl = "latest" # Kubernetes 官方命令行工具
helm = "latest" # 云原生 Helm 包管理器
kubeconform = "latest" # 高性能纯离线 K8s 清单 OpenAPI Schema 语法校验器
"aqua:cloudnative-pg/cloudnative-pg/kubectl-cnpg" = "latest" # CloudNativePG 官方 CLI 插件 (备份/状态/主从)

# --- 终端交互、资源审计与排错 ---
k9s = "latest" # 全功能终端 Kubernetes 交互式 TUI
stern = "latest" # 跨多 Pod 与命名空间日志正则聚合查看器
kube-capacity = "latest" # 4C8G 规格 CPU/内存 Requests & Limits 水位审计工具
