apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-agent-secret
  namespace: observability
spec:
  encryptedData:
    key: AgBWZlrOYZrHk46FyomI3GXVQG7gPra8/q0qcuSv9pr7pfWIRAUUNbYX2GVR5Wn9mzsiy4CiBTzeiKupmv3Z0F18D+kNKeiYaUVq5sCVuqp1lGyjmLpbTbbnrNHTnxutoD5KudRz4UfU0WDHGkZ97XaoCiEpqcGKNp1AmnVJaw/20Jkoy7P6FRZfWAdOaN0M9WZVDGBmP2DyaKr2X8/TLHq3BoZOH0qUCBBnoHSqBEi7qF2GcE6+e/Saji+h+4UUwOJ8/i12rWRnnRn9PcJlAsdZRAWRPHHj+MEHlbe+XtSFpWh96EmnkLfZ/xSfsrH1/2ueOtFudl6DObhaJ1ZJSdNe+1KMB939o8TbWcAzvWq+AZGKgKbdwKzVA4IHeC8Kz2wqMWlSSMfXN0svosbpGBm7oVpM6/QWRyMzGyuTXh0Y5py9SJrEJg6OF/6EC4s/hpv/O6Nf9k3Rd9VTXlAXEKC6+72j2P/tkeSIOIU14RI4zkFH1GkKuV89beo2cs8ARei7cZDIF7Pym/o3i1DdnvLMjnj+A52016lM2SLJJt9Folai6CGUbucv2QIHzyRMl5DG2ErDClzO3aCKv5iBGs6L9gDtBcrmBOlLonbs0xR7w6K5q5w51sAPS7U9+llL+I17e1qqjMwDbSdC85ojoEw6Irhyd0I0JNetGzZ5VTYkv06BsrPVLQ2pFTiTqX8gEkU=
    token: AgBjg0jlWWA8NvBr4sDhD0URyWOFjblUngBMiGgzhLqWKl1EIhsbjwTxYqwlpANpt0D22vwR8fc90XTpN1SRQj9okmmeBzBuqhoIa2LzzjJidJTaefUNGyFQk//pCelXc7BVJkoF7btSGC/wDCpQbWaYi+u/y+vc42eLIPWiEFE6sdwFb29OWRXuO/yKzVlJzQ52Pu8LILvKOCZ5x6DyutxTv5/evGzrKnZ7Gvu9poZ2vO20sZCObQGKbflzYkeazdsyGuq4UCiGWqH5esY5ZgvtzHuWoROwKuKkInZ0+1fiMZqSETvnno2pB/2eybNzZCkJ/ea0Xj8I/z0xDA7W/RihjjYrW3bjSym3xTHrV8LpR/RC8mYpLyPugIBwKFOnkXTNCCuQxcTmelB8hw7f8Vejk8nUlSpgHP4xKoQysWNpfMRudnyYR/SVvJgtYz8H9WU8iLIKoXcdLaRoN+RbuwTOtDPB/WwLZjI1g/2DkirXlQWw+iqZS12HxUHYYXss5Co1DDiJPQHu4KHadrR4mt+CuS7K8Ia8E6neqX1KFgamoxm64jTg0eomyhpIUS38hvXulI3UfFqBzTDkF3JUY0UMY18VxIZhMU3B0wzDz26uUlkQOHiQbqVsjAl+c2cHyYSbJNZ3lr9Hwnmpzg1q+ms1c/D/Rz7z5s6MNaJEdCIuyB7810Rrh1n08tw7PeQznO8=
  template:
    metadata:
      name: beszel-agent-secret
      namespace: observability
    type: Opaque
