apiVersion: v1
kind: Secret
metadata:
  name: authelia-secret
  namespace: security
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
# 生产环境中推荐使用 SOPS + Age 加密此文件 (命名为 authelia-secret.enc.yaml)
stringData:
  # Authelia 官方 Helm Chart 默认密钥挂载映射 (纯 SQLite3 + 加密 Cookie 架构)
  identity_validation.reset_password.jwt.hmac.key: "sUdz4hhhKPMhplagMREEsRtiRZ9yF1ldr3e5iJv8AQQqXUAe35gEmY8ycS4ffSwm"
  session.encryption.key: "481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM"
  storage.encryption.key: "481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM"
  # 环境变量兼容映射
  jwt-secret: "sUdz4hhhKPMhplagMREEsRtiRZ9yF1ldr3e5iJv8AQQqXUAe35gEmY8ycS4ffSwm"
  session-secret: "481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM"
  storage-encryption-key: "481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM"
  JWT_SECRET: "sUdz4hhhKPMhplagMREEsRtiRZ9yF1ldr3e5iJv8AQQqXUAe35gEmY8ycS4ffSwm"
  SESSION_SECRET: "481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM"
  STORAGE_ENCRYPTION_KEY: "481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM"
