# ==============================================================================
# Centrifugo 本地 Secret 与 Traefik IngressRoute (解耦自 Helm Chart)
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: valkey-secret
  namespace: messaging
type: Opaque
stringData:
  password: "redis_secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: centrifugo-secrets
  namespace: messaging
type: Opaque
stringData:
  token-hmac-secret-key: "768583f3-7205-4b36-aea3-32ca8dea4914"
  api-key: "aef5a17a-fdeb-48aa-b2c1-d490c62ff950"
  admin-password: "wt+7nmavPSAGroho3w/9ew=="
  admin-secret: "++WnV+LKf1vzZIfzMNqjbK/eb/DDqgnX42izczRWRqU="
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: centrifugo
  namespace: messaging
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`centrifugo.mso.lol`)
      kind: Rule
      services:
        - name: centrifugo
          port: 8000
  tls:
    certResolver: cloudflare
