services:
  gotify:
    image: gotify/server:3.1
    container_name: gotify
    restart: always
    ports:
      - "${GOTIFY_PORT:-8380}:80"
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
      - TZ=${TIMEZONE:-Asia/Shanghai}
    volumes:
      - "${DATA_PATH}gotify:/app/data"
    networks:
      - backend
