---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-app-credentials
  namespace: database
spec:
  encryptedData:
    password: AgA1clcUuut9f+QbjrTb3Wm8DpunNOX2JLCmEgw0djDTO8ElOAxHte7ZCzldDdgGXDlXpmzhhG5GXMQ6hGehAGJEaO1E2TfHpmytOYQQMnDqnyKYNvTTpZJYqPQN8OPjGjdWbWBalCsGStKu0acdbrPRumMk6AcwLkklm1N74BLUxsds7Km7Ku4SnVzIIoAHbePEyyj/9FFuW2ac46ulGE9nGyG3niwAzDA+0aziWTSp76bxsHL3PvBi+L4ztVEytqGICvyi/jyu0X1hhkz01CZjZqY7Hs7HFDZpT/qutCxHkIZ8xwhLdthV/gzKM0KaQo9StUbeiwgzkYX0ndYLjnoS6PC/lxHngtZfuyxXUeZ/dhPnjzbN7nDvV4YMVcMWagAxc/+jwMTuQ/w9AwAD709lCKyp9cryeyWr4tCOs7Ek2iTAc5DN+tgsubalUFfpxvedepk7/qiHPQ8Y1DitgpFDMeDEkmOV67CLzdYKrRCgNeHOdUJv96PPJn4TXte4uLokU47U1qL56oJi3734aZgcHRfRm7xZlwnFmA5YsF/YOwg+a0bMQZmlTJHypw6TUme3sGS4qdtATtKIcDqwnsTemVMqYXCf3QHH3Y/TWODX3BuCvw30cvqjZjqsiWPjG9r/RmAKm3KvY1zd/KwXHdzguXXELvyxytra1yaI7lUrBAiaC20f8HkHnohPgBtSXWNceA/Kag1atDWUVkp2kUkUH3GE
    username: AgBLHPd/xoODMZXqxGm5//0dMzhBmPkk6w1YtnCIfP2k4/isnZ6EmyVPa1Vwq7h4NzAuK6tJELLvuDioKl/XxVDMgNHq4PlYxt9Vk5v4afur0uZI3PJT+aKKFIK8vM/XiPezkEOyC9uk5O4N1va4RcDjWCTws20skLsMRcNc/zJIbiLKTCWg/qdK0VQVWJqQU4NxMarQwgd8+ZLBA5eECh8wtPWJsOYW0HKWVJflO5/NiaJ94UvTbBsFKfnu5iruOPRtFOUFC07T/Msh+96h9aFIMQPFMruyhopVsRvd+dryX8LcW03ixg7gK+yxYf1+F3cFZJF1cV4im9gFhhvlH7PBVj7f2uuBgEQkIhTyWDeq8dcHHJlIxlkPZ057n22I0e6UWZHIQ0mx32v3FJZyIQ5xErO7jtejLirhVHmCGzea+viSu3clkbYZWm1C4FTiKHShxyQw2AwtrYkVljPVeDplnqx783mMjcQqZxkCjy3q//VYfBbM5+XwEdMwpcJzIooMgbw0WpJV7oS44LxD8ORrllF01nZWsGlEKl+3iaweESZIF/DDWnIc9X/g9m4BWPky09Yzs3W9ZSvt6CzmbmiB0WM4PxtmjVexW2ApNU0rvLBy+0SSs7mrYy304purtXqd+ucpWlj+VJwpRmqHTIRFOlgJgu7r0wkq5iu8fOs36j6/0KOJ4N1T1WO37+/RNAHDG/M=
  template:
    metadata:
      name: postgres-app-credentials
      namespace: database
    type: kubernetes.io/basic-auth
