apiVersion: v1
kind: Secret
metadata:
  name: garage-s3-credentials
  namespace: database
type: Opaque
# 生产环境中推荐使用 SOPS + Age 加密此文件 (命名为 s3-credentials.enc.yaml)
stringData:
  ACCESS_KEY_ID: "GKfd16f76e81fb861a868a01b9b19452ad"
  SECRET_ACCESS_KEY: "18d5eda476ff7fb88f0bec38eae3a5e468020ae6dfc610defe2f3f72a65c4339"
