---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-s3-credentials
  namespace: database
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAyZb12m/lKdPKn6iz78S0NOS7ntsbKw9GLQ59uE5pM94goHzQFtApu9orAO4Vz9tQfa0bXhkoeS2IgZDrlfoUOkYkpkYh9EFrquUULo/HPXSwAMZ0596yn7IDYvRLQ5uhoIr1MOIhfFuYFSwu4qL7/ofvnOPKHVTkGlPM/fwPpX/zJPpj+o68pP23r/7RiCKNTqiSjqmBJScO/RTGWTuqfkaCgwCcAQYCGfiLtRyxiEuty6LmDWpNVqxgPWc2ytkcWNW6fQlK6WOQWWFt9MNrpa57FpccTTOvOi9gHQ05u3AgNaTO9A4ANEZHPiRxVll0P5w++mFEXqtLFZtQ3bAmVty7jPBPYYg9m1Fm2nH1A1a7vjRzNSdBfRNc0vcPzmqvG55Ln3B/0XhMrrVTXrvIsJ0EGrsrKjrCSyVioDvlXsPsr7d0oKyK5bN7LSLplpwSWIxSooap85ILUSIJiuBMGloU/WaVfFi0c9W2g0evwxUmQHxzG1gi5niPu8YHvIHVTwqypXgWx/3/7wlfCs1cdMQB/4p7vQZomP+HiCOQ87MatybdHdwPYxCn5kaLF5+Jf0U6RUQ8+vB9Jx2H6c/tUCRWJaB1NhjHgiTfqYlBZE8F9ozU6+roJPrFGMXBLL8gs88+Rc8VJxAF5jflyyjLsgLfzdLRap4Z6i7ljfPWCsOTTtZpbKLIi0pRE3x64Hf/dsYvOdcIzMX3pZ1HMMeu0ChshRx3TLoHnV0XKn0VpBSUv
    SECRET_ACCESS_KEY: AgBKWg2+8FxM+rlvEnixoosLbE9tSE9TxT/vXM6kH7WZ1AGh5476TR8Jhx7rCeRn0JdnUtRHqtNuHNWeSu2yc/UkicIFXDNyP2R6zLMo3ENpOXbG0vj6lT104wv0Ckdrp4zX8992bJQBfdxD6MjUhKahJBR9UWBgQ9js0Y1EKY8jhyuCkK1z/73fg99ZJPu3HOUtRLRILHipa6HfO7e0v+2rjaNb9BDRJgF8ijAJkXhk9ZvlGZeCKcs2BYz0pnhAjUnXf3dkhoSxq/aNFLLumU5AvTavDoZ920gsLfqfxgDDlk9rBYLBtAV3KKEIYHV/59xOKILM9cZ9YoRSnuHfOKsUTdkB3GAGhq85n7bxPskJGJysUmI/BejD3KNFQNBcF1q1S1q+/9/vGLan/fLqeSJDzHDYej/D1f6OsjliMpHMmvNAkZQds+wwrwiUa4NNaL/6MDXUkYmt3j0BHXnKOFZcFivE0+bJKycAmY9VK3wxESHMvPqRifKDkbBvhVexn6o5RUZSLpuS9ZkVSvIruQWT73C7FBJCMFvHARr7PQvocWLagJ4RY3to6G/MWi2h9vbVbOJXEZQjeypeB75K4R6MlKIBX/aDR/i4EwKnWSeZ/X11NOU1oDO9frinSXY4OeLlTZSBEyPjV7hSc9BP6cPgwZUUv5FMXFiE8rEvj1f+draU0C209Hpl/fJuoSyzqDOCTWrcIzSFTjl1lOwWJWyODWZYlgT88UvLKzqgwwyT9FRvR/qIIiI2dAdmWJoYq4tEh9d+rRdBTim/tmRRydF+
  template:
    metadata:
      name: garage-s3-credentials
      namespace: database
    type: Opaque
