# ==============================================================================
# CrowdSec 本地 Secret 与 Traefik Bouncer 中间件 (解耦自 Helm Chart)
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-secrets
  namespace: security
type: Opaque
stringData:
  traefik-bouncer-key: "5c30d79acd60832cd4c6712dfbb472e2"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: security
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      logLevel: "INFO"
      crowdsecLapiUrl: "http://crowdsec-service.security.svc:8080"
      crowdsecLapiHeaderAuthKey: "5c30d79acd60832cd4c6712dfbb472e2"
      redisCacheEnabled: false
