---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-secrets
  namespace: security
spec:
  encryptedData:
    traefik-bouncer-key: AgCfbGNf9hvZ2v44crmAQURHJhbEwBrgHYxwqhaOe/EcSQvkqya31GoQeWWBwAEJWZBgQlnnEnQvetbZB7HC1M9m6ZDZSS+oldUp4Lxx38+RHD8K6WG/HQhDob/J1wFA9L3Cg3weADViFXFMu3F4dvxge1PxRyPMdARRwIhTQ+3pmzMhdai369FdJBsnfa5Tvm6qmhawcMoa2V/+ac0VJYwEA74sJbiXp8cSJuPZoPFqVIzIWTBW/cKe8pKoJV2ws4W4Uo9EgkkYG61zie3q8QD/dw2u5XFXWPoGnd/ZdIj87UQC3Ad1PZJSJlnHEoAXwzUwvCeuxnS77dpTZO9TUHgDBS0NLgKp/WixPcO1S3kBodOdSkmAFraS08HadW3r9NOl8ViDJ4dSKZRaiPPYZqdbmssaDuQyi+CqX+agZC8mPISXB4RVc1pV0qZRdLNno9O3iEETMrSeW1/s34F0hasqubUSIA0K7x8TztBmypr7kKAEsdeialMZwq7jfqapGY0u58Z9pke6THRSkngK0fK0u8s/voSOOO6gBxVA+BAjClNA3+Y9PQEKRDtC8cX/Ro3otL3aUHFshf3q50QeXPSi0cxkiHZW6DQdQ+Ib35rOE0g3S5YrqIKVTFJ+/oOwOipqSd9NsKN1jsupD1p/TSWrCHVFlyZhu1a8MGDI0RgDZx40it8Z+Ftfzpcx47rxfQaeiwo/RvEvmW8tmrNwBHB7IWFG0vbqXIv5cDBOsJe8Xw==
  template:
    metadata:
      name: crowdsec-secrets
      namespace: security
    type: Opaque
