apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  # 覆盖默认服务器块中的本地解析规则（确保集群内部直接回环解析本集群入口）
  hosts.override: |
    hosts {
        127.0.0.1 mso.lol
        127.0.0.1 api.mso.lol
        127.0.0.1 auth.mso.lol
        127.0.0.1 search.mso.lol
        127.0.0.1 s3.mso.lol
        127.0.0.1 gateway.mso.lol
        127.0.0.1 argocd.mso.lol
        fallthrough
    }
