apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  # 占位文件避免缺少 *.server 导致 CoreDNS 周期性打印 No files matching *.server 告警
  empty.server: ""
  # 将 *.mso.lol 与 mso.lol 优雅重写映射到 Traefik 网关 Service，利用 K8s 内部 DNS 原生解析 ClusterIP
  # 彻底规避硬编码 IP 与动态子域名维护成本
  rewrite.override: |
    rewrite stop {
        name regex (.*)\.mso\.lol traefik.traefik.svc.cluster.local
        answer auto
    }
    rewrite stop {
        name exact mso.lol traefik.traefik.svc.cluster.local
        answer auto
    }
