---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    token: AgAYXSpCP3Wq7aNvPKUo2LL4svWa9vJPC7Mu6LnM/yy+fFelAeQANJ83rqM4E2o2EjkftAs7FXxzI4EXTWo5nYLx5E3/zPWO82E8y8Gqbo3axixSOtIxmA4teZQHLufedb1hwQUv7//JPvOEFxjYNrGE3x6/LH3M7FeXuKpob3l+5RC1Pp3YeICwlw4bQ+DUuwDug2EOBWQv9fDucAUHn+/xlTfj4feSTlSr1qGR6gVT0v7I2K3OqQ00Oo4hcSLDiQUsUkgImKALYC+6+T6EeeJODFR51UFiJ0rXJHhpZxs7MTFCoXIjFukqSdC56xsgqjuCh8dORrcD8QqRaekbrBhV3zmcPHTtC4kCFDFn6YxByzDVDyG3OJ2eEtbSjJLiBIMEe/Lixx2DZLOYyoModNG9swAL+4ajltyIR4U5/C+xcwPWwG3WusKtksMX2g2tLahVcO/8kmwQtWmD2a2kjpUbGwPaU0EaTuoJu/yyzGe6bCjNASSLY2M3KsHHq6OcJw6iD7KoWDYNzJmPJPkP0NLH9fGI3bIc4d+iRIBJKV6kJbtzc5P7YRMMOnXKB1MIWOHiS14a+Hz0BFv1cFWv+YP4poDybhSRG0lrltHmDY2q87zecI2NZlTjWcxz69pYFuVhQ37U5inZUzey+FYatNOrP3GHMtEadLv65Q8rlKNQN4Ax5UUi8cEi5XhcLBGWdk6Ne4qvkuO4O2/H5rPikHR+y3C+8IBD+swFrBTWH75oczN0SJoVyDUp
  template:
    metadata:
      name: cloudflare-api-token
      namespace: traefik
    type: Opaque
