services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10
    restart: always
    ports:
      - "8180:8080"
    volumes:
      - ${CONFIG_PATH}docker-tools/dozzle/users.yml:/data/users.yml
    environment:
      DOZZLE_REMOTE_HOST: tcp://docker-socket-proxy:2375
      #      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ENABLE_SHELL: true
      DOZZLE_NO_ANALYTICS: true
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
    depends_on:
      - docker-socket-proxy
    networks:
      - backend
      - frontend
