---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: imgproxy-secrets
  namespace: media
spec:
  encryptedData:
    key: AgAsYuJDAhvZLXyKmuOqtXPeUG68MvZgiNdfLBPY6b+myPgg7JiWxtRJORudbt8QwRdJFSglUgmzz0aKt/odwTSDPJGQ8lN9yWl9ihhxubItH5/VLdQU+QS9JIbjy4auFmJxFu9cldiLKzC6yGNFl6dIpEpyr42cNYbKuLbYdkiSmYA2HjKOEKyLtLfZpEhJsUBJnOqzpFAnoBpq8ChpSNXnkIDvxBZKH/TXimMY4ywoCN1lYWmCkvfT74JQxzt/tKoga7McSs7IOsbc/i0JsnpqNzxOJWI48kDOHs4QEtaBRJ3zGJ8Rj7DuLu60gJ079pvwcvEkEvODh9wzCKdWmHZZ8hRyrIl1un/TXQipxD33O85zg14NKgr8lu6V4Pigb0bBFCJV5JVAL6xbjjN7Gr4txBf4KQH1BjBlktYJWteOYdAkiwFQQ+OkFKnviYpqT8Gsv+4kVxD7MjG1itYYmhoETOJy2t7IX3SnG0KxchTnRY872Rfv++zY5a/GDXPo00WWX+eSOpQdvR4+F9Wh1H/z3gn4/l/hAoOWQAia2O0lSAhwlKVtMkBexFIrSI34sUdnJNeTPs9vZAabjyAkKIXpOXeKkqJQKh3RYxqs0/mA55RJ/Hj43OHOLae+qaLDkNCOV1AUb6hoOHb2J8jgDs+3H5LldWGTgfI2a/Fw2tm9BAsPgbXfn6gy2fUB78Fp9YLrV2jbVjVSPfEI1MmsKzlwNBOOFC+Eie6d/8nkmTpz0VXhksUSavEQy/ZW75cDAokGyE+uS1eAL2Rt7q2hmqKZ
    salt: AgB51DUTDFbNsUcfFxThKVkTYu9UHeNXPr/poWuc3KqaDLyPX5VACk33T15JyreRIQdUC4ucpFjosx+BVwsJ69UC9JzRZsacfQg+bvaYybA2PAmeH8zTWaPdROmc4tSFQxw70q5e2dQF2WJ4LLaufj9G/ZFVaIQYkuMTTSqOaq01aQxEmv8WcZAiP+9bv/i05qZBF1OMjPnSxQsHdl1BfV3ItE+W2XFT/FzCLx4j8dx9Ou+KdGViuU/d/vS1GO3PK6AS2gmm1AIKaM/5yYUMa3KYzrugP9nj5EO/pugCZOZ9RIojfDdANTjlxDeDCp7/sOep1WbsCkdWJGBrNpXPuJiZumyx5k7qsLrzwCaCPb7vuE5n/tN2lgWBap47bDqLNGd0mBiC6TQ271McjN11cuXeVucNA3k5OG4UJLHXssP5oqBrvTAFxT0ZDc6VT0x4RCPmT6ZzFlR6z054se+8QLz8GyUSHCrLcMJ9/qk2cKYIYhWjtSpPFLA4DQxy1zqJOvef95hvD05yMZJGqu/w+d7W25dvCKQ9U6UtbVEVFvtxdajXyavpR0RKRTG1QdoWmrY9SKGbHfkYULv45bYM6yjV/e5svMW/D4mtF0KBA16cWWDKmPpyY+0325+zZTd5NpU766gFq41yZ63uNm/FO6ilZ5rPL5cheJwEl2tWaBDsMET6eNVg0PCi+LV8i9i0XUNaV7GPRhpOy5OiWGG5oNWw7o54PBa29bHwxS39ScfBuyQ+ccvxn01bCUHpwvlRjOZzkCsMhJLFXE94RPS8v44a
  template:
    metadata:
      name: imgproxy-secrets
      namespace: media
    type: Opaque
