metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/meta-snapshots"
db_engine = "lmdb"
replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "5368ea7003a35eebcaf25c618fab1c3ad1dbae01b8fc5d1fba4c737e5a955751"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
# 请将 yourdomain.com 替换为您的实际 SITE_ADDRESS 域名
root_domain = ".s3.yourdomain.com"

[s3_web]
bind_addr = "[::]:3902"
# 请将 yourdomain.com 替换为您的实际 SITE_ADDRESS 域名
root_domain = ".s3.web.yourdomain.com"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "A5Q4zO27rJ4Xlz/Ojuoj2obCbL1aFGe9SugGt066loQ="
metrics_token = "VZaAJqzH0ZhWjOGSen95AEyOgJEVYf/engNWdKIxoo4="
metrics_require_token = true

[k2v_api]
api_bind_addr = "[::]:3904"
