---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meilisearch-master-key
  namespace: search
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBD6RArRLH6tfsaIOF1+yRyzk4yPZFIXMzxUbGlCg+WonLoyc2AB9+ZtrZq3DdponXb0tNrCwhl/lDX9k/bQ9yV0IkKuwG7e4Elb50sOXyygNe4XSqHWLZ7wtGtSYiRMGQXNz4pUcLD5EW01zYB6Q/k8IZm+lpj96LKPfUef4gMIZ5OHluWVlRibg6LeWWrckF7ZEk+5ruAJYdWfxx+aKRw9X6sneIEyZ4WuMUlgxQTMveHPsm7eOtIXHn63Qjspm4F7GdaCRNvrA3oCsjkMqQ0J7bDRplhrry7ZiFqDTLO61lMaS8x7LC1wZpNFu93nHZYRZQtvQdv5cEZD6QkMxa0eWI8G43aBy9TSC4XDevD2Lp7ZTp6385+yoFmTOjMU9oP+wBA7RmbaC21Oy/0M7/R8xWook7kT7XGoaypnF36rH03EGrRvLF8y+Za4V8mFBOEafQQczKkAhQVnaxq9x5BdYhL1FgYMNIt8L2kDOTVGFbvlp3ypkmuPTZeOjIF9fwcV2NhGRhqrWKDbYbOpAirF3N+zUMUC/XImCSAcU1Nh25S+XrsrSoRslkzLzz6lF6m5xZS257o7IgiYLGDUG7hZHp4af2/wCduQI6uIpk/Kv0lLPazEb6ppOKzRSuypNoluTkqXwlKvC0Wr6SO6kwyZtusa2J5gsBxDsxBv4SikcTWbVuXtGRzMye6rrrMnJv+l0ZKHoI0x7IFpf0hml28Ox1nxQQec8Sf3yjhlQu+nivo26bws+OCeamP
  template:
    metadata:
      name: meilisearch-master-key
      namespace: search
    type: Opaque
