services:
  meilisearch:
    build:
      context: .
      args:
        - TZ=${TIMEZONE:-Asia/Shanghai}
    container_name: meilisearch
    restart: always
    command: meilisearch --config-file-path /meili_config/config.toml
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    ports:
      - "7700:7700"
    volumes:
      - ${DATA_PATH}meili_data:/meili_data
      - ${CONFIG_PATH}database/meilisearch/config.toml:/meili_config/config.toml:ro
    networks:
      - frontend
      - backend
