services:
  authelia:
    image: authelia/authelia:4.39
    container_name: authelia
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - ${CONFIG_PATH}iam/authelia/config:/config
      - ${DATA_PATH}authelia:/data
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - TZ=${TIMEZONE}
      - DOMAIN=${SITE_ADDRESS}
      - JWT_SECRET=${AUTHELIA_JWT_SECRET:-sUdz4hhhKPMhplagMREEsRtiRZ9yF1ldr3e5iJv8AQQqXUAe35gEmY8ycS4ffSwm}
      - SESSION_SECRET=${AUTHELIA_SESSION_SECRET:-481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM}
      - STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY:-481F2EN0L2RQJHT882OSM481F2EN0L2RQJHT882OSM}
      - REDIS_HOST=${REDIS_HOST:-valkey}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_USER_NAME=${RESEND_USER_NAME:-resend}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:9091/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - valkey
    networks:
      - frontend
      - backend
