services:
  traefik:
    container_name: traefik
    image: traefik:v3.7
    restart: unless-stopped
    init: true
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - AUTHELIA_HOST=${AUTHELIA_HOST:-authelia:9091}
      - CROWDSEC_BOUNCER_KEY=${CROWDSEC_BOUNCER_KEY:-crowdsec-traefik-bouncer-dev-secret-key-32ch}
      - CROWDSEC_LAPI_HOST=${CROWDSEC_LAPI_HOST:-crowdsec:8080}
      - CROWDSEC_APPSEC_HOST=${CROWDSEC_APPSEC_HOST:-crowdsec:7422}
      - CF_DNS_API_TOKEN=${CF_API_TOKEN:-}
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${LEGO_EMAIL:-admin@${SITE_ADDRESS:-example.com}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_PATH}gateways/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${CONFIG_PATH}gateways/traefik/dynamic:/etc/traefik/dynamic:ro
      - ${DATA_PATH}ssl:/etc/traefik/certs:ro
      - ${DATA_PATH}traefik/acme:/etc/traefik/acme
      - ${DATA_PATH}traefik/plugins-storage:/plugins-storage
      - ${LOG_PATH}traefik:/var/log/traefik
    ports:
      - "${TRAEFIK_PORT:-80}:80"
      - "${TRAEFIK_SSL_PORT:-443}:443"
      - "${TRAEFIK_SSL_PORT:-443}:443/udp"
    networks:
      - frontend
      - backend
