apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bgin-api
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.mso.lol`) && PathPrefix(`/docs`)
      kind: Rule
      priority: 20
      middlewares:
        - name: chain-auth
          namespace: traefik
      services:
        - name: bgin-api
          port: 3300
    - match: Host(`api.mso.lol`)
      kind: Rule
      priority: 10
      middlewares:
        - name: chain-api
          namespace: traefik
      services:
        - name: bgin-api
          port: 3300
  tls:
    certResolver: cloudflare
