apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - pvc.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - ingressroute.yaml

images:
  - name: ghcr.io/woailuoisme/gin-bun
    newTag: latest
