apiVersion: v1
kind: Secret
metadata:
  name: bgin-secret
  namespace: apps
type: Opaque
# 生产环境中推荐使用 SOPS + Age 加密此文件 (命名为 secret.enc.yaml)
stringData:
  DB_URL: "postgres://app:app_secret_password@postgres-cluster-rw.database.svc:5432/bgin?sslmode=disable"
  REDIS_URL: "redis://:redis_secret@valkey-primary.database.svc:6379/0"
  AWS_ACCESS_KEY_ID: "GKfd16f76e81fb861a868a01b9b19452ad"
  AWS_SECRET_ACCESS_KEY: "18d5eda476ff7fb88f0bec38eae3a5e468020ae6dfc610defe2f3f72a65c4339"
  IMGPROXY_KEY: "016bb66d0d40f8f746c0c327eca2232495bb367e90f5d0124329a0fea07c929b"
  IMGPROXY_SALT: "07c466cebbed802f7b449c67dfad29f393df60f09ffbd2af47462f88791e3ab5"
  MEILISEARCH_KEY: "bWaV7Z_2LHrn-t1LIJc3ENDT7R-svZ5tNMsuTifQfX0"
  RESEND_API_KEY: "rre_NgXq94T4_6d3LtsTaAf8wkuVzar8UaLnx"
  JWT_SECRET: "7a9e3b1c8f4d2e5a6b0c9d8e7f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f90"
  SEED_ADMIN_PASSWORD: "admin123!"
  CENTRIFUGO_API_KEY: "aef5a17a-fdeb-48aa-b2c1-d490c62ff950"
  CENTRIFUGO_SECRET: "768583f3-7205-4b36-aea3-32ca8dea4914"
